version: "3.7"

services:
  express:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/workspace:cached
      - shared-volume:/not-mount
    environment:
      TICKER_WRITE_FILE: /not-mount/test
    command: /bin/sh -c "while sleep 1000; do :; done"
  ticker:
    build:
      context: .
      dockerfile: ticker.Dockerfile
    environment:
      TICKER_WRITE_FILE: /mount/test
    volumes:
      - shared-volume:/mount

volumes:
  shared-volume:
